# ???????? ????????? ???????
index.path=search-index
lucene.version=9.9.1
index.ramBufferSizeMB=256
index.threads=4

# ????????? ??????
search.phraseSlop=2
search.defaultOperator=AND

# ????????? Tika
# ??????????? ????? ???????????? ?????? ???????? ?? OOM ?? ??????? PDF/XLSX
# ? ??????????? ? ????? ??? ????????.
tika.maxStringLength=200000
tika.timeoutSeconds=30

# OCR (?????????? ?????????????? ??????)
# ??????? ?????????????? Tesseract OCR: https://github.com/tesseract-ocr/tesseract
# ocr.language ?????? ???????? ?????? Tesseract ????? '+', ????????: rus+eng
# ??? ?????????? ???????? ???????: https://github.com/tesseract-ocr/tessdata
ocr.language=rus+eng
